### ISSUE TITLE
Error at bulk loading which avoid leemons to start

### ISSUE THREAD

**Issue by diegogd** [leemonade/leemons#8]
During first initialization of the docker it breaks during bulk-template initialization.

<details><summary>CLICK to see error log</summary>
<p>

#### This is the log after initializing all the plugins

```
docker-leemons-back-1          | 2022-07-20T17:00:26.506Z INFO    Listening on http://localhost:8080
docker-leemons-back-1          | 2022-07-20T17:00:27.898Z INFO    plugins.bulk-template emitted init-providers
docker-leemons-back-1          | 2022-07-20T17:00:27.898Z INFO    BULK Providers initialized
docker-leemons-back-1          | 2022-07-20T17:00:27.900Z DEBUG   BULK Starting Users plugin ...
docker-leemons-back-1          | 2022-07-20T17:00:28.460Z INFO    Creating center 'Leemons Spain'
docker-leemons-back-1          | 2022-07-20T17:00:28.501Z DEBUG   plugins.users emitted didCreateCenter 0ms
docker-leemons-back-1          | 2022-07-20T17:00:28.512Z INFO    plugins.bulk-template emitted init-centers
docker-leemons-back-1          | 2022-07-20T17:00:28.882Z INFO    Creating role 'profile:ca6cd058-f23e-4b1a-b602-ddd80cceaf79:role'
docker-leemons-back-1          | 2022-07-20T17:00:28.961Z INFO    Creating role 'ca6cd058-f23e-4b1a-b602-ddd80cceaf79:89440e2c-4825-4e56-8656-ef12e8dd0553'
docker-leemons-back-1          | 2022-07-20T17:00:28.973Z INFO    plugins.users emitted profile-permissions-change
docker-leemons-back-1          | 2022-07-20T17:00:29.295Z INFO    plugins.curriculum emitted permissions-change
docker-leemons-back-1          | 2022-07-20T17:00:29.304Z INFO    Creating role 'profile:5d1ff8ef-738a-4ee3-93ee-93fcd7f8f566:role'
docker-leemons-back-1          | 2022-07-20T17:00:29.384Z INFO    Creating role '5d1ff8ef-738a-4ee3-93ee-93fcd7f8f566:89440e2c-4825-4e56-8656-ef12e8dd0553'
docker-leemons-back-1          | 2022-07-20T17:00:29.398Z INFO    plugins.users emitted profile-permissions-change
docker-leemons-back-1          | 2022-07-20T17:00:29.421Z INFO    plugins.curriculum emitted permissions-change
docker-leemons-back-1          | 2022-07-20T17:00:29.439Z INFO    Creating role 'profile:1bc6559f-d439-4ec4-bffe-67eee6bdf816:role'
docker-leemons-back-1          | 2022-07-20T17:00:29.516Z INFO    Creating role '1bc6559f-d439-4ec4-bffe-67eee6bdf816:89440e2c-4825-4e56-8656-ef12e8dd0553'
docker-leemons-back-1          | 2022-07-20T17:00:29.528Z INFO    plugins.users emitted profile-permissions-change
docker-leemons-back-1          | 2022-07-20T17:00:29.561Z INFO    plugins.curriculum emitted permissions-change
docker-leemons-back-1          | 2022-07-20T17:00:29.577Z INFO    Creating role 'profile:ce9a7584-b08e-4b93-97d9-5dcf6995cc89:role'
docker-leemons-back-1          | 2022-07-20T17:00:29.632Z INFO    Creating role 'ce9a7584-b08e-4b93-97d9-5dcf6995cc89:89440e2c-4825-4e56-8656-ef12e8dd0553'
docker-leemons-back-1          | 2022-07-20T17:00:29.644Z INFO    plugins.users emitted profile-permissions-change
docker-leemons-back-1          | 2022-07-20T17:00:29.652Z INFO    plugins.bulk-template emitted init-profiles
docker-leemons-back-1          | 2022-07-20T17:00:29.674Z INFO    plugins.curriculum emitted permissions-change
docker-leemons-back-1          | 2022-07-20T17:00:29.989Z DEBUG   Batch processing users ...
docker-leemons-back-1          | 2022-07-20T17:00:29.989Z DEBUG   Adding user: Super
docker-leemons-back-1          | 2022-07-20T17:00:30.179Z INFO    User ADDED: Super
docker-leemons-back-1          | 2022-07-20T17:00:30.190Z DEBUG   Adding user: Estefanía
docker-leemons-back-1          | HTTPError: Response code 403 (Forbidden)
docker-leemons-back-1          |     at Request._onResponseBase (/monorepo/packages/leemons-utils/node_modules/got/dist/source/core/index.js:905:31)
docker-leemons-back-1          |     at Request._onResponse (/monorepo/packages/leemons-utils/node_modules/got/dist/source/core/index.js:940:24)
docker-leemons-back-1          |     at ClientRequest.<anonymous> (/monorepo/packages/leemons-utils/node_modules/got/dist/source/core/index.js:954:23)
docker-leemons-back-1          |     at /monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:49
docker-leemons-back-1          |     at AsyncHooksRunContextManager.with (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/BasicRunContextManager.js:59:17)
docker-leemons-back-1          |     at ClientRequest.wrapper (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:23)
docker-leemons-back-1          |     at Object.onceWrapper (node:events:642:26)
docker-leemons-back-1          |     at /monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:49
docker-leemons-back-1          |     at AsyncHooksRunContextManager.with (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/BasicRunContextManager.js:59:17)
docker-leemons-back-1          |     at ClientRequest.wrapper (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:23)
docker-leemons-back-1          |     at ClientRequest.emit (node:events:539:35)
docker-leemons-back-1          |     at ClientRequest.emit (node:domain:475:12)
docker-leemons-back-1          |     at ClientRequest.wrappedEmit (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/http-shared.js:187:21)
docker-leemons-back-1          |     at ClientRequest.origin.emit (/monorepo/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
docker-leemons-back-1          |     at HTTPParser.parserOnIncomingClient (node:_http_client:631:27)
docker-leemons-back-1          |     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
docker-leemons-back-1          |     at TLSSocket.socketOnData (node:_http_client:494:22)
docker-leemons-back-1          |     at TLSSocket.emit (node:events:527:28)
docker-leemons-back-1          |     at TLSSocket.emit (node:domain:475:12)
docker-leemons-back-1          |     at addChunk (node:internal/streams/readable:315:12)
docker-leemons-back-1          |     at readableAddChunk (node:internal/streams/readable:289:9)
docker-leemons-back-1          |     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
docker-leemons-back-1          |     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
docker-leemons-back-1          |     at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
docker-leemons-back-1          |   code: 'ERR_NON_2XX_3XX_RESPONSE',
docker-leemons-back-1          |   timings: {
docker-leemons-back-1          |     start: 1658336430297,
docker-leemons-back-1          |     socket: 1658336430303,
docker-leemons-back-1          |     lookup: 1658336430429,
docker-leemons-back-1          |     connect: 1658336430508,
docker-leemons-back-1          |     secureConnect: 1658336430672,
docker-leemons-back-1          |     upload: 1658336430673,
docker-leemons-back-1          |     response: 1658336430771,
docker-leemons-back-1          |     end: 1658336430774,
docker-leemons-back-1          |     error: undefined,
docker-leemons-back-1          |     abort: 1658336430779,
docker-leemons-back-1          |     phases: {
docker-leemons-back-1          |       wait: 6,
docker-leemons-back-1          |       dns: 126,
docker-leemons-back-1          |       tcp: 79,
docker-leemons-back-1          |       tls: 164,
docker-leemons-back-1          |       request: 1,
docker-leemons-back-1          |       firstByte: 98,
docker-leemons-back-1          |       download: 3,
docker-leemons-back-1          |       total: 482
docker-leemons-back-1          |     }
docker-leemons-back-1          |   }
docker-leemons-back-1          | }
docker-leemons-back-1          | HTTPError: Response code 403 (Forbidden)
docker-leemons-back-1          |     at Request._onResponseBase (/monorepo/packages/leemons-utils/node_modules/got/dist/source/core/index.js:905:31)
docker-leemons-back-1          |     at Request._onResponse (/monorepo/packages/leemons-utils/node_modules/got/dist/source/core/index.js:940:24)
docker-leemons-back-1          |     at ClientRequest.<anonymous> (/monorepo/packages/leemons-utils/node_modules/got/dist/source/core/index.js:954:23)
docker-leemons-back-1          |     at /monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:49
docker-leemons-back-1          |     at AsyncHooksRunContextManager.with (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/BasicRunContextManager.js:59:17)
docker-leemons-back-1          |     at ClientRequest.wrapper (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:23)
docker-leemons-back-1          |     at Object.onceWrapper (node:events:642:26)
docker-leemons-back-1          |     at /monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:49
docker-leemons-back-1          |     at AsyncHooksRunContextManager.with (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/BasicRunContextManager.js:59:17)
docker-leemons-back-1          |     at ClientRequest.wrapper (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:23)
docker-leemons-back-1          |     at ClientRequest.emit (node:events:539:35)
docker-leemons-back-1          |     at ClientRequest.emit (node:domain:475:12)
docker-leemons-back-1          |     at ClientRequest.wrappedEmit (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/http-shared.js:187:21)
docker-leemons-back-1          |     at ClientRequest.origin.emit (/monorepo/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
docker-leemons-back-1          |     at HTTPParser.parserOnIncomingClient (node:_http_client:631:27)
docker-leemons-back-1          |     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
docker-leemons-back-1          |     at TLSSocket.socketOnData (node:_http_client:494:22)
docker-leemons-back-1          |     at TLSSocket.emit (node:events:527:28)
docker-leemons-back-1          |     at TLSSocket.emit (node:domain:475:12)
docker-leemons-back-1          |     at addChunk (node:internal/streams/readable:315:12)
docker-leemons-back-1          |     at readableAddChunk (node:internal/streams/readable:289:9)
docker-leemons-back-1          |     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
docker-leemons-back-1          |     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
docker-leemons-back-1          |     at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
docker-leemons-back-1          |   code: 'ERR_NON_2XX_3XX_RESPONSE',
docker-leemons-back-1          |   timings: {
docker-leemons-back-1          |     start: 1658336430297,
docker-leemons-back-1          |     socket: 1658336430303,
docker-leemons-back-1          |     lookup: 1658336430429,
docker-leemons-back-1          |     connect: 1658336430508,
docker-leemons-back-1          |     secureConnect: 1658336430672,
docker-leemons-back-1          |     upload: 1658336430673,
docker-leemons-back-1          |     response: 1658336430771,
docker-leemons-back-1          |     end: 1658336430774,
docker-leemons-back-1          |     error: undefined,
docker-leemons-back-1          |     abort: 1658336430779,
docker-leemons-back-1          |     phases: {
docker-leemons-back-1          |       wait: 6,
docker-leemons-back-1          |       dns: 126,
docker-leemons-back-1          |       tcp: 79,
docker-leemons-back-1          |       tls: 164,
docker-leemons-back-1          |       request: 1,
docker-leemons-back-1          |       firstByte: 98,
docker-leemons-back-1          |       download: 3,
docker-leemons-back-1          |       total: 482
docker-leemons-back-1          |     }
docker-leemons-back-1          |   }
docker-leemons-back-1          | }
docker-leemons-back-1          | 2022-07-20T17:00:30.791Z ERROR   Response code 403 (Forbidden)
docker-leemons-back-1          | HTTPError: Response code 403 (Forbidden)
docker-leemons-back-1          |     at Request._onResponseBase (/monorepo/packages/leemons-utils/node_modules/got/dist/source/core/index.js:905:31)
docker-leemons-back-1          |     at Request._onResponse (/monorepo/packages/leemons-utils/node_modules/got/dist/source/core/index.js:940:24)
docker-leemons-back-1          |     at ClientRequest.<anonymous> (/monorepo/packages/leemons-utils/node_modules/got/dist/source/core/index.js:954:23)
docker-leemons-back-1          |     at /monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:49
docker-leemons-back-1          |     at AsyncHooksRunContextManager.with (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/BasicRunContextManager.js:59:17)
docker-leemons-back-1          |     at ClientRequest.wrapper (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:23)
docker-leemons-back-1          |     at Object.onceWrapper (node:events:642:26)
docker-leemons-back-1          |     at /monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:49
docker-leemons-back-1          |     at AsyncHooksRunContextManager.with (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/BasicRunContextManager.js:59:17)
docker-leemons-back-1          |     at ClientRequest.wrapper (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/run-context/AbstractRunContextManager.js:76:23)
docker-leemons-back-1          |     at ClientRequest.emit (node:events:539:35)
docker-leemons-back-1          |     at ClientRequest.emit (node:domain:475:12)
docker-leemons-back-1          |     at ClientRequest.wrappedEmit (/monorepo/node_modules/elastic-apm-node/lib/instrumentation/http-shared.js:187:21)
docker-leemons-back-1          |     at ClientRequest.origin.emit (/monorepo/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
docker-leemons-back-1          |     at HTTPParser.parserOnIncomingClient (node:_http_client:631:27)
docker-leemons-back-1          |     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
docker-leemons-back-1          |     at TLSSocket.socketOnData (node:_http_client:494:22)
docker-leemons-back-1          |     at TLSSocket.emit (node:events:527:28)
docker-leemons-back-1          |     at TLSSocket.emit (node:domain:475:12)
docker-leemons-back-1          |     at addChunk (node:internal/streams/readable:315:12)
docker-leemons-back-1          |     at readableAddChunk (node:internal/streams/readable:289:9)
docker-leemons-back-1          |     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
docker-leemons-back-1          |     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
docker-leemons-back-1          |     at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)
```

</p>
</details>

If after the error I try to stop the container and start them again I don't see anything after displaying the message `Listening on http://localhost:8000`

Following the documentation I used [data.xlsx](https://github.com/leemonade/leemons/files/9152275/data.xlsx) which I edited just changing the school name. And I put it at `my-leemons/packages/leemons-plugin-bulk-template/src/bulk/data.xlsx` path.

This problem can be reproduced with the [original file linked in the documentation](https://docs.google.com/spreadsheets/d/1dXX79cTzn2R9e9SRoL_pmmuw1EacxS_hm6XWUxGkQew/edit?usp=sharing).

**Comment by diegogd** [comment]
👍 I'll do it. 
Yesterday I tried to execute this from different architecture as initial tests were done with M1 arm architecture, but doing under x86 happens too.

**Comment by johan-fx** [comment]
It was a bug in the spreadsheet, which referenced several images that no longer exists.

The references in the spreadsheet has been fixed and, in addition, a fix has been added in [this commit](https://github.com/leemonade/leemons/commit/43775a0932cc3b2ea2e5855b2d2ad3779f3d7ff5) to clear empty data before import.

Please pull last changes and download the spreadsheet again 😄

**Comment by diegogd** [comment]
I can confirm the loading process now executes correctly.  🎉

However after full boot I can't still see nothing. When I go to `http://localhost:8080` or `http://localhost:3000` I get redirected to `/admin` path, and nothing else happens. I don't see any error in the docker log or in the browser console. Any clue about how to continue?

**Comment by diegogd** [comment]
This problem is solved in `dev` branch. In `master` both frontend and backend url send you to the /admin url. Even when the demo data is loaded.

With `dev` branch if the demo data is loaded then frontend is not redirected to admin, otherwise it send you to /admin to initialize a new account.

Now I can see Leemons working 🎉
